name: CI
on:
  push:
jobs:
  build-linux:
    name: Build Go Binary linux amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu
          make build_linux_amd64
          make build_linux_arm64
      - name: upload bookmark-linux-amd64
        uses: actions/upload-artifact@v2
        with:
          name: bookmark-linux-amd64
          path: |
            bookmark-linux-amd64
      - name: upload bookmark-linux-arm64
        uses: actions/upload-artifact@v2
        with:
          name: bookmark-linux-arm64
          path: |
            bookmark-linux-arm64

  build-darwin:
    name: Build Go Binary macos amd64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download frontend files
        uses: actions/download-artifact@v2
        with:
          name: frontend_dist_files
          path: frontend/build
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - run: |
          make build_drawin_arm64
          make build_drawin_amd64
      - name: upload bookmark-darwin-arm64
        uses: actions/upload-artifact@v2
        with:
          name: bookmark-darwin-arm64
          path: |
            bookmark-darwin-arm64
      - name: upload bookmark-darwin-amd64
        uses: actions/upload-artifact@v2
        with:
          name: bookmark-darwin-amd64
          path: |
            bookmark-darwin-amd64

  release:
    needs: [build-darwin, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Download linux arm64 bookmark
        uses: actions/download-artifact@v2
        with:
          name: bookmark-linux-arm64
          path: /tmp
      - name: Download linux amd64 bookmark
        uses: actions/download-artifact@v2
        with:
          name: bookmark-linux-amd64
          path: /tmp
      - name: Download darwin amd64 bookmark
        uses: actions/download-artifact@v2
        with:
          name: bookmark-darwin-amd64
          path: /tmp
      - name: Download darwin arm64 bookmark
        uses: actions/download-artifact@v2
        with:
          name: bookmark-darwin-arm64
          path: /tmp
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          allowUpdates: true
          artifacts: "/tmp/bookmark*"
          token: ${{ secrets.GITHUB_TOKEN }}